stages

diff --git a/test/Jenkinsfile_test b/test/Jenkinsfile_test
--- a/test/Jenkinsfile_test
+++ b/test/Jenkinsfile_test
@@ -3,7 +3,7 @@ pipeline {
     
 
     stages {
-        stage('STAGE1') {
+        stage('STAGE1a') {
             steps {
                 catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                     echo "This is the step 1"
@@ -14,6 +14,25 @@ pipeline {
                 }
             }
         } 
+
+        stage('STAGE1b') {
+            steps {
+                script {
+                    try {
+                        sh '''
+                            sleep 5
+                            exit 1
+                        '''
+                    }
+                    catch(err) {
+                        echo "Error caught: ${err}"
+                        currentBuild.result = 'SUCCESS'
+                        currentStage.result = 'FAILURE'
+                    }
+                }
+            }
+        }
+        
         stage('PARALLEL TESTING') {
             parallel {
                 stage('WINDOWS TESTING') {
